language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: I5BCeIsqvNyzRmKqMAA6OopUfYtm1bun0SqLduA6Iu4T2kxfjFSpxMXfDcCICHNn5Kxbe11KqiRSvIkqFrpuHT6vSHebx2zz/4ZnRnSz+WilvxZpGZ11YJiiUg2JuW7Bmxhev3POEDl1RFcAMGGSNv5i42rJTMJU0qIovu75YdiCrhJnf+edvlJvXgQ6jQM0lUAe3m/9gSfrBG+PTxbRtq3lifQYdpOza47iWIgNuvhcX2z0iiWmpuQREQT7geWVEBo5EdfSXuy22+4ESPRroYtgOJlFo9U29IRayF+dHF5SRc9ytOl0FOcY4J4Uqa0J2x9yVtaVrOuVPjakHu8xzmfKYNFvYQ1v38ndQp0m8/aVdrS6236kHm/D182wM9AcofUfUtybqsVc0TBBD0Z4unpRkmx064OsBDbdJKNnxjmpcGGxOfv9n4yS4iCaris4cXT5JNcUyKXZDKa2+rWmbnxDxbzLulictEFAluY79y4xpFXXbNhLQIYCmxlAF+It7ITD4Iapd3f4TS+sjhym0xT1JSeyd6VyCnO0+tjmt36gUwa1BDqzqh2fJ5BmFcR6MplcPfsa3dVYCpBTZAAlYJlpbUC2dmbEcNl1MCaimYtsfqF+Gv5c3tAixCSfcZaUSLJOFUFV2jr2bVHf2jP4WWggd6oSLR/mvdsP+FN1uEs=
  file:
    - 'is-word-character.js'
    - 'is-word-character.min.js'
  on:
    tags: true
